<?
    // Set page title.
    $this->headTitle($this->translate('Contents'));
?>

<style>

	#static-content li {
		margin-bottom: 10px;
	
	}


</style>

<div id="static-content" class="<?=$this->layoutClass('mainbody')?>">

   <?//=$this->render("home/contents/". $this->section . "_" . $this->layout()->userLang. ".phtml")?>
      
<?=$this->flashmessages()?>

<h2>Cadastro de Revista no Diretório Seer</h2>

<form class="form-horizontal" action="" method="post">
  <div class="form-group">
    <label class="col-sm-3 control-label" for="dbname">Nome Revista:</label>
    <div class="col-sm-9">
      <input type="text" name="nomerevista" class="form-control"/>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="dbname">Url Revista:</label>
    <div class="col-sm-9">
      <input type="text" name="nomerevista" class="form-control"/>
    </div>
  </div>
  
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="instituicao">Instituição:</label>
    <div class="col-sm-9">
      <select name="instituicao" class="form-control">
        <option value="UNB">UNB</option>
        <option value="UCB">UCB</option>
		<option value="UFMG">UFMG</option>
		<option value="UFG">UFG</option>
      </select>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="endereco">CEP:</label>
    <div class="col-sm-9">
      <input type="text" name="cep" id="cep" class="form-control"/>
	      <input type="button" id="buttoncep" class="form-control" value="Pesquisar Cep"/>
	 </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="endereco">Endereço da Instituição:</label>
    <div class="col-sm-9">
      <input type="text" name="endereco" id="endereco" class="form-control"/>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="bairro">Bairro:</label>
    <div class="col-sm-9">
      <input type="text" name="bairro" id="bairro" class="form-control"/>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="cidade">Cidade:</label>
    <div class="col-sm-9">
      <input type="text" name="cidade" id="cidade" class="form-control"/>
    </div>
  </div>
  
  
   <div class="form-group">
    <label class="col-sm-3 control-label" for="uf">UF:</label>
    <div class="col-sm-9">
      <select name="uf" class="form-control" id="select_uf">
        <option value="AC">AC</option>
        <option value="AL">AL</option>
		<option value="AP">AP</option>
		<option value="AM">AM</option>
        <option value="BA">BA</option>
        <option value="CE">CE</option>
		<option value="DF">DF</option>
		<option value="ES">ES</option>
        <option value="GO">GO</option>
        <option value="MT">MT</option>
		<option value="MS">MS</option>
		<option value="MG">MG</option>
        <option value="PR">PR</option>
        <option value="PB">PB</option>
		<option value="PA">PA</option>
		<option value="PE">PE</option>
        <option value="PI">PI</option>
        <option value="RJ">RJ</option>
		<option value="RN">RN</option>
		<option value="RS">RS</option>		
        <option value="RO">RO</option>
        <option value="RR">RR</option>
		<option value="SC">SC</option>
		<option value="SE">SE</option>	
		<option value="SP">SP</option>	
		<option value="TO">TO</option>			
      </select>
    </div>
  </div>

  <div class="form-group">
    <label class="col-sm-3 control-label" for="emailrevista">Email Revista:</label>
    <div class="col-sm-9">
      <input type="text" name="emailrevista" class="form-control"/>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="editorgerente">Editor Gerente:</label>
    <div class="col-sm-9">
      <input type="text" name="editorgerente" class="form-control"/>
    </div>
  </div>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="areacnpq">Área Cnpq:</label>
    <div class="col-sm-9">
      <input type="text" name="areacnpq" class="form-control"/>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="periodicidade">Periodicidade:</label>
	<div class="col-sm-9">
      <select name="periodicidade" class="form-control">
        <option value="Bimestral">Bimestral</option>
        <option value="Trimestral">Trimestral</option>
		<option value="Quadrimestral">Quadrimestral</option>
		<option value="Anual">Anual</option>	
      </select>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="anoinicioseer">Ano Início do Periódico no SEER:</label>
    <div class="col-sm-9">
      <input type="text" name="anoinicioseer" class="form-control"/>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="issnimpresso">ISSN Impresso:</label>
    <div class="col-sm-9">
      <input type="text" name="issnimpresso" class="form-control"/>
    </div>
  </div>  
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="issneletronico">ISSN Eletrônico:</label>
    <div class="col-sm-9">
      <input type="text" name="issneletronico" class="form-control"/>
    </div>
  </div>
	
  <div class="form-group">
    <label class="col-sm-3 control-label" for="doi">Digital Object Identifier - DOI:</label>
    <div class="col-sm-9">
      <input type="text" name="doi" class="form-control"/>
    </div>
  </div>  
  
 <div class="form-group">
    <label class="col-sm-3 control-label" for="periodicoeletronicovigente">Periódico Eletrônico Vigente:</label>
	<div class="col-sm-9">
      <select name="periodicoeletronicovigente" class="form-control">
        <option value="Sim">Sim</option>
        <option value="Nao">Não</option>
      </select>
    </div>
  </div> 
  
  <div class="form-group" id="div_indexadobasedados">
    <label class="col-sm-3 control-label" for="indexadobasedados">Indexado em Base de Dados:</label>
	<div class="col-sm-9">
      <select name="indexadobasedados" class="form-control" id="select_indexadobasedados">
        <option value="Nao">Não</option>
		<option value="Sim">Sim</option>
      </select>
    </div>
  </div>
  
  <div class="form-group" id="div_indexadobasedadosquais">
    <label class="col-sm-3 control-label" for="indexadobasedadosquais">Indexado em Base de Dados. Quais:</label>
	<div class="col-sm-9">
      <select name="indexadobasedadosquais" class="form-control">
        <option value="Scielo">Scielo</option>
        <option value="Latindex">LatIndex</option>
		<option value="Outros">Outros</option>
      </select>
    </div>
  </div>
  
  <div class="form-group">
    <label class="col-sm-3 control-label" for="doi">Versão:</label>
    <div class="col-sm-9">
      <input type="text" name="versao" class="form-control"/>
    </div>
  </div>  
  
  
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Submit') ?>" />
    </div>
  </div>
  
</form>
             
<!-- /.main -->     
</div>

<script type="text/javascript">

$(document).ready(function(){
	
    
	var valueSelected = $("#select_indexadobasedados option:selected").val();
	if (valueSelected=="Sim"){
		$("#div_indexadobasedadosquais").show();
	}else{
		$("#div_indexadobasedadosquais").hide();
	}

	$("#select_indexadobasedados").change(function(){
		var optionSelected = $("option:selected", this);
		var valueSelected = this.value;
		
		if (valueSelected=="Sim"){
			$('#div_indexadobasedadosquais').show();
		}else{
			$('#div_indexadobasedadosquais').hide();
		}
	});
	
	$("#buttoncep").click(function(){
		var cep = $("#cep").val();
		var url="http://api.postmon.com.br/v1/cep/"+cep;
		$.getJSON(url, function( data ) {
			$.each(data, function(key, valor) {
				if(key=="logradouro"){
					$("#endereco").val(valor);
				}else if(key=="bairro"){
					$("#bairro").val(valor);
				}else if(key=="cidade"){
					$("#cidade").val(valor);				
				}else if(key=="estado"){
					$("#select_uf option").each(function() {
						this.selected=(this.value == valor);

					});
				}
			});
		});
	});

});

</script>



